### PR TITLE
Tv os support

### LINKED ISSUE #152: Adding tvOS support
My team is exploring integrating this SDK for Over-the-Air support to help reduce the releases we need to make just for translations. Our code base is shared between iOS and tvOS which may defeat the purpose if Over-the-Air isn't supported on one platform. Is there a timeline for providing tvOS support?

### PR DESCRIPTION
**Pull request by serhii-londar**
Closes #152

### CODE REVIEW

**Comment by chrispomeroyhale** [comment]
Wonderful! I also independently got this working on tvOS using your BaseAPI 0.2.0 changes for Over-the-Air. I wasn't sure how to support Real-Time Previews on tvOS from a UI perspective, and our team's main concern is getting Over-the-Air working on tvOS for the moment.

So my changes were simpler: There were some files in the Core subspec that needed changes for tvOS but weren't actually used for just Over-the-Air functionality. I relocated those files to where I thought they might better live, so they could be excluded from Over-the-Air. The second thing I did was remove the Starscream dependency from Core and into Real-Time Previews. I found that reduce this SDK's core memory footprint in roughly half.

Would be happy to contribute if that would be helpful

**Comment by serhii-londar** [comment]
Hi @chrispomeroyhale. Thanks for your comment. I'm not sure that we can simply get rid of Starscream dependency for Core and CrowdinProvider subspecs, but I think that is a good point to do that in future(The API podspec should be spitted). 

Also, could you help us with testing tvOS support by adding SDK from 'tvOS-support' branch:
pod 'CrowdinSDK', :git => 'https://github.com/crowdin/mobile-sdk-ios.git', :branch => 'tvOS-support'

**Review by andrii-bodnar — APPROVED** [review]

**Comment by chrispomeroyhale** [comment]
Apologies for the delay, I've had an extended winter break. When I compile using the 1.4.0 release I get the following error on UIView.cw_present and on getTopViewController in Toast.swift:

> 'shared' is unavailable in application extensions for tvOS: Use view controller based solutions where appropriate instead.

In my demo branch I had resolved errors like these by relocation these two files into the Settings directory since I wrongly thought the Settings Cocoapod subspec was a requirement of Real-Time Preview. I see this PR uses compiler conditionals, maybe that's the better way to go until the the podspecs can be re-organized so that Real-Time Preview can be excluded at compile time?

**Comment by chrispomeroyhale** [comment]
I'm not sure some of these files are actually used in Core. So something like this?
https://github.com/chrispomeroyhale/mobile-sdk-ios/commit/e3f1ef23006912a2e86432b43a9464c09ad28e81

**Comment by serhii-londar** [comment]
@chrispomeroyhale Do you use sdk in app extension? Have you tried "Working with App Extensions" section in readme?

**Comment by serhii-londar** [comment]
> I'm not sure some of these files are actually used in Core. So something like this?
> [chrispomeroyhale@e3f1ef2](https://github.com/chrispomeroyhale/mobile-sdk-ios/commit/e3f1ef23006912a2e86432b43a9464c09ad28e81)

I'm not sure it will work fine as CrowdinAPI podspec has Starscream dependency. Is it work for using only translation delivery feature?

**Comment by chrispomeroyhale** [comment]
> @chrispomeroyhale Do you use sdk in app extension? Have you tried "Working with App Extensions" section in readme?

👍  Good call-out, thank you! We do have a Notification Service extension and a tvOS Top Shelf extension. I excluded this pod from the extensions and it built fine

> I'm not sure it will work fine as CrowdinAPI podspec has Starscream dependency. Is it work for using only translation delivery feature?

For the moment our team is only interested in over-the-air translation delivery. Starscream does have a small startup time and memory usage penalty. Even though it may be a dependency for the CrowdinAPI podspec, I'm not seeing calls into Starscream except for the optional Real-Time Preview podspec, so it appears to be unused in this case? I can open a separate issue on this?

**Pull request merged**
