### PR TITLE
Adding information regarding the App Extensions

### PR DESCRIPTION
**Pull request by d4r1091**
Hi, I'm changing this readme to include the information when it happens to work with `Cocoapods` and `Service Extensions`.

Hope you'll find it useful.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Thanks @d4r1091 ! And congrats on your first contribution! :tada:

**Comment by andrii-bodnar** [comment]
@d4r1091, please add indentation for added list item as it is in first and second list items :)

**Comment by andrii-bodnar** [comment]
@d4r1091 , sorry for the unclear explanation, I meant like this :)

screenshot-github com-2020 01

**Comment by d4r1091** [comment]
I've also added the some minor changes @andrii-bodnar

**Comment by andrii-bodnar** [comment]
@d4r1091, thank you! 
We are happy to accept contributions to the Crowdin iOS SDK and want to send you our stickers as a present on your first PR. Could you please send us your address using [this contact form](https://crowdin.com/contacts)?

**Pull request merged**
